CREATE TABLE IF NOT EXISTS tb_servicos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_veiculos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  servicos_id BIGINT,
  placa VARCHAR(7) NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  marca VARCHAR(255) NOT NULL,
  cor VARCHAR(50),
  ano INT,
  preco DECIMAL(10, 2),
  FOREIGN KEY (servicos_id) REFERENCES tb_servicos(id)
);

CREATE TABLE IF NOT EXISTS tb_contas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL,
  valor DECIMAL(10, 2) NOT NULL,
  vencimento DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_funcionarios (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cpf CHAR(11) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  salario DECIMAL(10, 2) NOT NULL
);
